name: Run Anime News Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PASS_TOKEN }}  # Use the PASS_TOKEN for authentication

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ensure posted_titles.json exists
        run: |
          if [ ! -f posted_titles.json ]; then
            echo "[]" > posted_titles.json  # Create an empty JSON array if it doesn't exist
          fi

      - name: Run Anime News Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Store your bot token in GitHub Secrets
          CHAT_ID: ${{ secrets.CHAT_ID }}      # Store your chat ID in GitHub Secrets
        run: |
          python animebot.py

      - name: Commit and push posted_titles.json
        env:
          PASS_TOKEN: ${{ secrets.PASS_TOKEN }}
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git remote set-url origin https://MRMK0FC:${{ secrets.PASS_TOKEN }}@github.com/MRMK0FC/animebot.git
          git add posted_titles.json
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "Update posted_titles.json"
            git push origin main
          fi
