name: Anime News Bot

on:
  schedule:
    - cron: '*/30 * * * *'  # Runs every 30 minutes
  workflow_dispatch:  # Allows manual triggering

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Restore posted_titles.json from cache
        id: cache-posted-titles
        uses: actions/cache@v3
        with:
          path: posted_titles.json
          key: posted-titles-${{ runner.os }}-${{ hashFiles('posted_titles.json') }}
          restore-keys: |
            posted-titles-${{ runner.os }}-

      - name: Run Anime News Bot
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}  # Store your bot token in GitHub Secrets
          CHAT_ID: ${{ secrets.CHAT_ID }}      # Store your chat ID in GitHub Secrets
        run: |
          python animebot.py

      - name: Save posted_titles.json to cache
        if: always()  # Ensure this step runs even if the previous step fails
        uses: actions/cache@v3
        with:
          path: posted_titles.json
          key: posted-titles-${{ runner.os }}-${{ hashFiles('posted_titles.json') }}
